# Generated by Django 5.0 on 2024-11-23 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0009_alter_blog_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paltform', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
